const RecurringTransaction = require('../models/RecurringTransaction');
const Transaction = require('../models/Transaction');
const { startOfDay } = require('./dateUtils');

const addMonth = (dateValue) => {
  const next = new Date(dateValue);
  next.setMonth(next.getMonth() + 1);
  return startOfDay(next);
};

const processDueRecurringTransactions = async (userId) => {
  const now = startOfDay(new Date());
  const recurringDocs = await RecurringTransaction.find({
    userId,
    active: true,
    nextRunDate: { $lte: now },
  });

  for (const recurring of recurringDocs) {
    let nextRunDate = startOfDay(recurring.nextRunDate);

    while (nextRunDate <= now) {
      const existing = await Transaction.findOne({
        userId,
        recurringSourceId: recurring._id,
        date: nextRunDate,
      });

      if (!existing) {
        await Transaction.create({
          title: recurring.title,
          amount: recurring.amount,
          type: recurring.type,
          category: recurring.category,
          date: nextRunDate,
          userId,
          recurringSourceId: recurring._id,
          isAutoGenerated: true,
        });
      }

      nextRunDate = addMonth(nextRunDate);
    }

    recurring.nextRunDate = nextRunDate;
    await recurring.save();
  }
};

module.exports = {
  processDueRecurringTransactions,
};
